name: Publish to Pypi
on:
  push:
    branches:
      - master

env:
  REPOSITORY_URL: https://test.pypi.org/legacy/

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    concurrency: push

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: ${{ secrets.PYPI_USERNAME }}
          repository_password: ${{ secrets.PYPI_PASSWORD }}
